name: Testes FastAPI CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Ajuste para a versão que você utiliza (ex: '3.10', '3.11')

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        # Adicione 'sqlalchemy' aqui
        pip install fastapi uvicorn pytest python-multipart httpx sqlalchemy
        
        # IMPORTANTE: Se você tiver um arquivo requirements.txt, use o comando abaixo:
        # pip install -r requirements.txt
        
        # Adicione aqui outras dependências manuais se necessário:
        # pip install passlib python-jose[cryptography]

    - name: Rodar testes
      run: |
        # Define o PYTHONPATH para incluir o diretório raiz do projeto
        # Isso permite que o Python encontre os módulos 'backend.users.app.main' e 'backend.orders.app.main'
        PYTHONPATH=$(pwd ) pytest
